server:
  servlet:
    context-path: ${context:/codenjoy-balancer}

mvc:
  cache-period: 259200

log:
  debug: false
admin:
  login: admin
  password: admin
email:
  hash: secureSoul
score:
  update:
    time: 10000
sender:
    pool.size: 100
game:
  type: bomberman
  servers:
    - location: localhost:8080
      schema: http
      basicAuthUser: admin@codenjoyme.com
      basicAuthPassword: admin
  room: 10
  start-day: "2020-03-01"
  end-day: "2020-03-31"
  finalists-count: 10
  finale-time: "19:00"