version: '3.3'

services:
   codenjoy_db:
     image: postgres:11.1
     container_name: codenjoy-database
     volumes:
       - ./content/database:/var/lib/postgresql/data
#P#     ports: 
#P#       - "2352:5432"
     restart: always
     environment:
         POSTGRES_DB: codenjoy
         POSTGRES_USER: codenjoy
         POSTGRES_PASSWORD: secureDBPassword
     networks:
         codenjoy:
             ipv4_address: 172.28.1.4
   
#D#   pgadmin:
#D#     image: dpage/pgadmin4
#D#     container_name: pgadmin
#D#     ports: 
#D#       - "3251:80"
#D#     environment:
#D#         PGADMIN_DEFAULT_PASSWORD: securePGAdminPassword
#D#         PGADMIN_DEFAULT_EMAIL: your@email.com
   
#B#   codenjoy_balancer_frontend:
#B#     depends_on:
#B#       - codenjoy_balancer
#B#     image: vreshch/codenjoy-lb
#B#     container_name: codenjoy-balancer-frontend
#B##P#     ports: 
#B##P#       - "8001:80"
#B#     networks:
#B#         codenjoy:
#B#             ipv4_address: 172.28.1.5

#B#   codenjoy_balancer:
#B#     depends_on:
#B#       - codenjoy_db
#B#     image: apofig/codenjoy-balancer:1.0.28
#B#     container_name: codenjoy-balancer
#B#     build:
#B#        context: .
#B#        dockerfile: Dockerfile-balancer
#B#     command: java -jar /usr/local/jetty/start.jar -Ddatabase.type=postgre #L# sqlite
#B#     volumes: 
#B##L#       - ./content/codenjoy/database:/var/lib/jetty/database
#B#       - ./config/codenjoy:/var/lib/jetty/config
#B#       - ./logs/codenjoy/codenjoy-balancer.log:/var/lib/jetty/logs/codenjoy-balancer.log
#B##P#     ports: 
#B##P#       - "127.0.0.1:8001:8080"
#B#     restart: always
#B#     networks:
#B#         codenjoy:
#B#             ipv4_address: 172.28.1.3

#C# comment this block if you need only balancer
   codenjoy_server:
     depends_on:
       - codenjoy_db
     image: apofig/codenjoy-contest:1.0.28
     container_name: codenjoy-contest
     build:
        context: .
        dockerfile: Dockerfile-contest
     command: java -jar /usr/local/jetty/start.jar -Ddatabase.type=postgre #L# sqlite
     volumes: 
#L#       - ./content/codenjoy/database:/var/lib/jetty/database
       - ./config/codenjoy:/var/lib/jetty/config
       - ./logs/codenjoy/codenjoy-contest.log:/var/lib/jetty/logs/codenjoy-contest.log
#P#     ports: 
#P#       - "127.0.0.1:8002:8080"
     restart: always
     networks:
         codenjoy:
             ipv4_address: 172.28.1.2

   nginx:
     depends_on:
#B#       - codenjoy_balancer
       - codenjoy_server
     image: nginx
     container_name: nginx
     volumes: 
#B#       - ./config/nginx/codenjoy-balancer.conf:/etc/nginx/conf.d/codenjoy-balancer.conf
       - ./config/nginx/codenjoy-contest.conf:/etc/nginx/conf.d/codenjoy-contest.conf      #C#
       - ./config/nginx/domain.conf:/etc/nginx/conf.d/domain.conf
       - ./config/nginx/ssl.conf:/etc/nginx/ssl.conf
       - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
       - ./config/nginx/.htpasswd:/etc/nginx/.htpasswd
       - ./cert:/usr/share/ca-certificates/extra
     ports: 
#A#       - "443:443" 
       - "80:80"   
     restart: always   
     networks:
         codenjoy:
             ipv4_address: 172.28.1.1
     
networks:
    codenjoy:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16
